    
    create table agendamento_vacina (
       id int8 generated by default as identity,
        data_agendamento timestamp not null,
        is_vacina_tomada boolean not null,
        tipo_vacina varchar(255) not null,
        usuario_id int8 not null,
        primary key (id)
    );
    
     create table vacina (
       id int8 generated by default as identity,
		nome varchar(255) not null,
        primary key (id)
    );
    
    create table feedback (
       id int8 generated by default as identity,
        data date not null,
        comentario text not null,
        usuario_id int8 not null,
        primary key (id)
    );
    
    create table perfil (
       usuario_id int8 not null,
        perfis varchar(7) not null
    );
    
    create table usuario (
       id int8 generated by default as identity,
        cpf varchar(11) not null unique,
        email varchar(255) not null unique,
        bairro varchar(255),
        cep varchar(11),
        cidade varchar(255),
        complemento varchar(255),
        endereco varchar(255),
        numero varchar(255),
        is_ativo boolean,
        nome varchar(255) not null,
        senha varchar(255) not null,
        telefone varchar(11) not null,
        estado varchar(255),
        primary key (id)
    );
    
    alter table if exists agendamento_vacina 
       add constraint fk_agendamento_vacina_usuario_id 
       foreign key (usuario_id) 
       references usuario;
    
    alter table if exists feedback 
       add constraint fk_feedback_usuario_id 
       foreign key (usuario_id) 
       references usuario;
    
    alter table if exists perfil 
       add constraint fk_perfil_usuario_id 
       foreign key (usuario_id) 
       references usuario;
    
