  
    create table carteira_vacinacao (
       id int8 generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    );

  ALTER TABLE public.usuario
    ADD COLUMN carteira_vacinacao_id bigint unique;
    
    create table vacina_tomada (
       id int8 generated by default as identity,
        data date not null,
        nome varchar(255) not null,
        carteira_vacinacao_id int8 not null,
        primary key (id)
    );

    
    alter table if exists usuario 
       add constraint fk_usuario_carteira_vacinacao_id
       foreign key (carteira_vacinacao_id) 
       references carteira_vacinacao;

    
    alter table if exists vacina_tomada 
       add constraint fk_vacina_tomada_carteira_vacinacao_id
       foreign key (carteira_vacinacao_id) 
       references carteira_vacinacao;